GuardaCapitaldaCultura2027/Models/RestricaoCovid.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GuardaCapitaldaCultura2027.Models
{
    public class RestricaoCovid
    {
        [Key]
        public int RestricaoCovidId { get; set; }

        [Required(ErrorMessage = "Por favor, insira o seu Nome")]
        [Display(Name = "Descrição")]
        [StringLength(500, MinimumLength = 20, ErrorMessage = "A descrição deve ter entre 20 e 500 caracteres")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Por favor, insira a data inicial")]
        [Display(Name = "Início")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DataInicio { get; set; }

        [Required(ErrorMessage = "Por favor, insira a data final")]
        [Display(Name = "Final")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DataFim { get; set; }
    }
}

GuardaCapitaldaCultura2027/Controllers/RestricaoCovidsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using GuardaCapitaldaCultura2027.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace GuardaCapitaldaCultura2027.Controllers
{
    public class RestricaoCovidsController : Controller
    {
        private readonly GuardaEventosBdContext _context;
        private readonly RestricoesCovid restricoesCovid;

        public RestricaoCovidsController(GuardaEventosBdContext context)
        {
            _context = context;
            restricoesCovid = new RestricoesCovid(context);
        }

        // GET: RestricaoCovids
        public async Task<IActionResult> Index(int pagina = 1)
        {
            restricoesCovid.Paginacao.PaginaAtual = pagina;
            restricoesCovid.ListaRestricoes = await _context.RestricaoCovid.Skip((restricoesCovid.Paginacao.PaginaAtual - 1) * restricoesCovid.Paginacao.ElementosPorPagina).Take(7).ToListAsync();
            return View(restricoesCovid);
        }

        // GET: RestricaoCovids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restricaoCovid = await _context.RestricaoCovid
                .FirstOrDefaultAsync(m => m.RestricaoCovidId == id);
            if (restricaoCovid == null)
            {
                return NotFound();
            }

            return View(restricaoCovid);
        }

        // GET: RestricaoCovids/Create
        [Authorize(Roles = "Admin, GestorEventos")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: RestricaoCovids/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Create([Bind("RestricaoCovidId,Descricao,DataInicio,DataFim")] RestricaoCovid restricaoCovid)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restricaoCovid);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(restricaoCovid);
        }

        // GET: RestricaoCovids/Edit/5
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restricaoCovid = await _context.RestricaoCovid.FindAsync(id);
            if (restricaoCovid == null)
            {
                return NotFound();
            }
            return View(restricaoCovid);
        }

        // POST: RestricaoCovids/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Edit(int id, [Bind("RestricaoCovidId,Descricao,DataInicio,DataFim")] RestricaoCovid restricaoCovid)
        {
            if (id != restricaoCovid.RestricaoCovidId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restricaoCovid);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestricaoCovidExists(restricaoCovid.RestricaoCovidId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restricaoCovid);
        }

        // GET: RestricaoCovids/Delete/5
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restricaoCovid = await _context.RestricaoCovid
                .FirstOrDefaultAsync(m => m.RestricaoCovidId == id);
            if (restricaoCovid == null)
            {
                return NotFound();
            }

            return View(restricaoCovid);
        }

        // POST: RestricaoCovids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restricaoCovid = await _context.RestricaoCovid.FindAsync(id);
            _context.RestricaoCovid.Remove(restricaoCovid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestricaoCovidExists(int id)
        {
            return _context.RestricaoCovid.Any(e => e.RestricaoCovidId == id);
        }
    }
}

GuardaCapitaldaCultura2027/Views/RestricaoCovids/Create.cshtml
@model GuardaCapitaldaCultura2027.Models.RestricaoCovid
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;
@{
    ViewData["Title"] = "Create";
}

<h4 class="alert-light">@Localizer["covid"] </h4>
<hr />

<div class="col-md-6 text-left">
    <fieldset class="border p-4 list-inline-item">
        <legend class="w-auto text-center font-weight-bold">@Localizer["covidF"]</legend>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">@Localizer["Descrição"]</label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">@Localizer["DataInicio"]</label>
                <input asp-for="DataInicio" class="form-control" />
                <span asp-validation-for="DataInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">@Localizer["DataFim"]</label>
                <input asp-for="DataFim" class="form-control" />
                <span asp-validation-for="DataFim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value=@Localizer["covidF"] class="btn btn-primary" />
            </div>
        </form>
    </fieldset>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">@Localizer["Voltar"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GuardaCapitaldaCultura2027/Views/RestricaoCovids/Delete.cshtml
@model GuardaCapitaldaCultura2027.Models.RestricaoCovid
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;
@{
    ViewData["Title"] = "Delete";
}

<center>
    <fieldset class="border p-4" style="width:fit-content;">
        <legend class="w-auto text-left">@Localizer["ffff"]</legend>
        <div class="row" style="width:fit-content; padding-left: 20px; padding-right:20px;">
            <table>
                <tr>
                    <td>
                        @Localizer["Descricao"]
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Descricao)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Localizer["DataInicio"]
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DataInicio)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Localizer["DataFim"]
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DataFim)
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</center>
<br />
<div>
    <a asp-action="Index" class="btn btn-secondary">@Localizer["Voltar"]</a> |
    <a class="btn btn-danger" data-toggle="modal" data-target="#confirmacaoApagar">@Localizer["Eliminar"]</a>
</div>

<div id="confirmacaoApagar" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header"><span> @Localizer["ffff"] </span></div>
            <div class="modal-body"><h6> @Localizer["Tem"]  <b> @Localizer["mesmo"] </b>  @Localizer["ads"] </h6></div>
            <div class="modal-footer">
                <form asp-action="Eliminar">
                    <input type="hidden" asp-for="@Model.RestricaoCovidId" />
                    <input asp-action="Eliminar" value=@Localizer["Eliminar"] type="submit" asp-route-id="@Model.RestricaoCovidId" class="btn btn-danger" />
                    <a class="btn btn-info" data-dismiss="modal" aria-label="Close">@Localizer["Fechar"] </a>
                </form>
            </div>
        </div>
    </div>
</div>

GuardaCapitaldaCultura2027/Views/RestricaoCovids/Details.cshtml
@model GuardaCapitaldaCultura2027.Models.RestricaoCovid
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{
    ViewData["Title"] = "Details";
}


<h4 class="alert-light">@Localizer["Details"] </h4>
<div>
    <h4>@Localizer["RestricaoCovid"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Localizer["Descricao"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class="col-sm-2">
            @Localizer["DataInicio"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInicio)
        </dd>
        <dt class="col-sm-2">
            @Localizer["DataFim"]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataFim)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RestricaoCovidId">@Localizer["Edit"]</a> |
    <a asp-action="Index">@Localizer["Voltar"]</a>
</div>

GuardaCapitaldaCultura2027/Views/RestricaoCovids/Edit.cshtml
@model GuardaCapitaldaCultura2027.Models.RestricaoCovid
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;
@{
    ViewData["Title"] = "Editar";
}
<form enctype="multipart/form-data" asp-action="Edit">
    <div class="col-md-6 text-left">
        <fieldset class="border p-4 list-inline-item">
            <legend class="w-auto text-left">@Localizer["EV"]</legend>
            <div class="row">
                <div class="col-md-6" style="max-width:100% !important; flex:auto;">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="RestricaoCovidId" />
                    <div class="form-group">
                        <label  class="control-label"> @Localizer["Descricao"]</label>
                        <input asp-for="Descricao" class="form-control" />
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label"> @Localizer["DataInicio"]</label>
                        <input asp-for="DataInicio" class="form-control" />
                        <span asp-validation-for="DataInicio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  class="control-label"> @Localizer["DataFim"]</label>
                        <input asp-for="DataFim" class="form-control" />
                        <span asp-validation-for="DataFim" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <center>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-secondary">@Localizer["Voltar"]</a> |
                    <input type="submit" value=@Localizer["Guardar"] class="btn btn-success" />
                </div>
            </center>
        </fieldset>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GuardaCapitaldaCultura2027/Views/RestricaoCovids/Index.cshtml
@model GuardaCapitaldaCultura2027.Models.ViewModels.RestricoesCovid
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{ ViewData["Title"] = "Index"; }

<fieldset class="border p-4">
    <legend class="w-auto text-left">@Localizer["LA"]</legend>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Localizer["Descricao"]
                </th>
                <th>
                    @Localizer["DataInicio"]
                </th>
                <th>
                    @Localizer["DataFim"]
                </th>
                <th>
                    <form id="pesquisaform" asp-action="Index">
                        <div>
                            @{
                                string pesquisa = "";
                                try
                                {
                                    pesquisa = string.IsNullOrEmpty(Context.Request.Form["pesquisa"]) ? string.Empty : Context.Request.Form["pesquisa"].ToString();

                                }
                                catch (Exception ex)
                                {
                                    Console.WriteLine(ex.Message);
                                }
                                finally
                                {
                                    if (string.IsNullOrEmpty(pesquisa))
                                    {
                                        pesquisa = ViewData["pesquisa"] as string;
                                    }
                                }
                                <input type="search" id="pesquisabox" autofocus oninput="this.form.submit();" onfocus="this.value = '@(pesquisa)'" onchange="this.form.submit()" name="pesquisa" style="margin-right:10px; border: 2px solid #167ce9;font-size: 1.2em;text-align: center;outline:none !important;border-radius: 20px;background-color:transparent;" />
                                <div style="display:none">
                                    @(ViewData["pesquisa"] = pesquisa)
                                </div>
                            }
                            <!--<input type="submit" class="icon-pesquisa fa-7x" value="&#xf002;" style="font-family: FontAwesome;height:35px;width:35px;background-color:transparent;margin-top:1px; border: 2px solid #167ce9;font-size: 1.2em;text-align: center;border-radius: 20px;outline:none !important" />-->
                        </div>
                    </form>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ListaRestricoes.Where(evt =>
            {
                return (!string.IsNullOrWhiteSpace(ViewData["pesquisa"]?.ToString())) ?
                  (evt.RestricaoCovidId.ToString().ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower()) ||
                  evt.Descricao.ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower()) ||
                  evt.DataInicio.ToString().ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower()) ||
                  evt.DataFim.ToString().ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower())) : true;
            }).ToList())
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataFim)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.RestricaoCovidId" class="btn btn-secondary" style="background-color:goldenrod;border-color:goldenrod;">  @Localizer["Edit"] </a> |
                        <a asp-action="Delete" asp-route-id="@item.RestricaoCovidId" class="btn btn-danger"> @Localizer["Eliminar"]  </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</fieldset>
<br />
<p>
    <a asp-action="Create" class="btn btn-primary"> @Localizer["covid"] </a>
</p>

<div>
    @{ if (Model.Paginacao.PaginaAtual > 1 && Model.Paginacao.PaginaAtual != 2)
        {
            <a title="Início" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? 1 : Model.Paginacao.PaginaAtual})"><span class="icon-prev"><i style="color:black" class="fas fa-angle-double-left"></i></span></a>
            <span>&nbsp;</span>
            <a title="Página Anterior" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? Model.Paginacao.PaginaAtual-1 : Model.Paginacao.PaginaAtual })"><span class="icon-prev"><i style="color:black" class="fas fa-angle-left"></i></span></a>
            <span>&nbsp;</span> }
        else if (Model.Paginacao.PaginaAtual > 1 && Model.Paginacao.PaginaAtual == 2)
        {
            <a title="Página Anterior" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? Model.Paginacao.PaginaAtual-1 : Model.Paginacao.PaginaAtual })"><span class="icon-prev"><i style="color:black" class="fas fa-angle-left"></i></span></a>
            <span>&nbsp;</span> }

        if (Model.Paginacao.PaginaAtual > 2)
        {
            @Html.ActionLink((Model.Paginacao.PaginaAtual - 1).ToString(), "Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual - 1) }, new { @style = "font-family: 'Varela Round';color:black;font-weight:bolder;" })
            <span>&nbsp;</span> }

        <span style="font-family: 'Varela Round';color:#167ce9;font-weight:bolder;">@Model.Paginacao.PaginaAtual.ToString()</span>
        <span>&nbsp;</span> if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas - 1)
        {
            @Html.ActionLink((Model.Paginacao.PaginaAtual + 1).ToString(), "Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual + 1) }, new { @style = "font-family: 'Varela Round';color:black;font-weight:bolder;" })
            <span>&nbsp;</span> }

        if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas && Model.Paginacao.PaginaAtual + 1 < Model.Paginacao.TotalPaginas)
        {
            <a title="Página Seguinte" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.PaginaAtual + 1 : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-right"></i></span></a>
            <span>&nbsp;&nbsp;</span>
            <a title="Última Página" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.TotalPaginas : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-double-right"></i></span></a>
            <span>&nbsp;&nbsp;</span> }
        else if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas && Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas)
        {
            <a title="Página Seguinte" href="@Url.Action("Index", "RestricaoCovids", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.PaginaAtual + 1 : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-right"></i></span></a>
            <span>&nbsp;&nbsp;</span> } }
</div>