GuardaCapitaldaCultura2027/Controllers/CulturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace GuardaCapitaldaCultura2027.Controllers
{
    public class CulturaController : Controller
	{
		[HttpPost]
		public IActionResult SelecionarCultura(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}
}

GuardaCapitaldaCultura2027/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using GuardaCapitaldaCultura2027.Models.ViewModels;

namespace GuardaCapitaldaCultura2027.Controllers
{
    public class EventosController : Controller
    {
        private readonly GuardaEventosBdContext _context;
        private readonly Eventos Eventos;

        public EventosController(GuardaEventosBdContext context)
        {
            _context = context;
            Eventos = new Eventos(context);
        }

        // GET: Eventos
        public async Task<IActionResult> Index(int page = 1)
        {
            Eventos.Paginacao.PaginaAtual = page;
            Eventos.ListaEventos = await _context.Eventos.Include(evt => evt.Municipio).Skip((Eventos.Paginacao.PaginaAtual - 1) * Eventos.Paginacao.ElementosPorPagina).Take(5).ToListAsync();
            return View(Eventos);
        }

        // GET: Eventos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Eventos.Include(evt => evt.Municipio)
                .FirstOrDefaultAsync(m => m.EventoId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // GET: Eventos/Create
        public IActionResult Create()
        {
            ViewData["municipios"] = new SelectList(_context.Municipio, "MunicipioId", "Nome");
            return View();
        }

        // POST: Eventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventoId,MunicipioId,Name,Descricao,Data_realizacao,Imagem,Lotacao_max,Lotacao_Ocupada")] Evento evento)
        {
            if (!string.IsNullOrWhiteSpace(Request.Form.Files["Imagem"].FileName))
            {
                var stream = Request.Form.Files["Imagem"].OpenReadStream();
                byte[] imagem = new byte[stream.Length];
                stream.Read(imagem);
                evento.Imagem = imagem;
                ModelState.Remove("Imagem");
            }

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Eventos.Include(evt => evt.Municipio).Where(evt => evt.EventoId == id).FirstOrDefaultAsync();
            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventoId,MunicipioId,Name,Descricao,Data_realizacao,Imagem,Lotacao_max,Lotacao_Ocupada")] Evento evento)
        {
            if (id != evento.EventoId)
            {
                return NotFound();
            }

            if (!string.IsNullOrWhiteSpace(Request.Form.Files["Imagem"].FileName))
            {
                var stream = Request.Form.Files["Imagem"].OpenReadStream();
                byte[] imagem = new byte[stream.Length];
                stream.Read(imagem);
                evento.Imagem = imagem;
                ModelState.Remove("Imagem");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.EventoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Eventos
                .FirstOrDefaultAsync(m => m.EventoId == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Eventos.FindAsync(id);
            _context.Eventos.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventoExists(int id)
        {
            return _context.Eventos.Any(e => e.EventoId == id);
        }
    }
}

GuardaCapitaldaCultura2027/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IViewLocalizer Localizer;

<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Guarda Eventos </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/img/logo.JPG" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/galery.css" rel="stylesheet" />

    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->

    <style>

        .mynav_navbar {
            overflow: hidden;
            background-color: gray;
            font-family: Arial, Helvetica, sans-serif;
        }



            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: gray;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }


        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }



            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 14px 16px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }



            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: grey;
            }



        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }



            .mynav_dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }



                .mynav_dropdown-content a:hover {
                    background-color: #ddd;
                }



        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }
    </style>
</head>
<body id="page-top">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-0">

        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a asp-controller="Home" asp-action="Index">
                <img src="~/img/LOGO-EVENTOS.png" style="width:100px; height:50px;" asp-controller="Home" asp-action="Index" />
            </a>
            <!--<button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Toggle button -->
            <button class="navbar-toggler"
                    type="button"
                    data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <!-- <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>-->
            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left links -->
                <ul class="navbar-nav ml-auto">

                    <li class="navbar-nav ml-auto">
                        <div class="collapse navbar-collapse" id="navbarResponsive">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-controller="Home" asp-action="Sobre">@Localizer["SobreNos"]</a></li>
                                @{
                                    if (SignInManager.IsSignedIn(User))
                                    {
                                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-controller="Reservas" asp-action="Index">@Localizer["Reservas"]</a></li>
                                    }
                                }
                                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-controller="Eventos" asp-action="Index">@Localizer["Eventos"]</a></li>
                                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-controller="Contactos" asp-action="Create">@Localizer["Contactos"]</a></li>
                            </ul>
                            <partial name="_LoginPartial.cshtml" />
                            <div class="mynav_dropdown text-black-50">
                                <button class="mynav_dropbtn">
                                    <a class="text-black-50">@Localizer["SlctLinguagem"]</a>
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="mynav_dropdown-content">
                                    @await Html.PartialAsync("_SelecionarLinguagemPartial")
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <header class="mt-3 text-center">
        <div class="m-0"></div>
        <div class="container ">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </header>

    <!-- Footer-->
    <!-- Footer -->
    <footer class="bg-light text-center text-lg-start">
        <!-- Grid container -->
        <div class="container p-4">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0 col-1-3 left">
                    <h5 class="text-left">@Localizer["Descrição"]</h5>
                    <p class="text-justify">
                        @Localizer["DescriText"]
                        <br />
                        <a asp-controller="Municipios" asp-action="Index">@Localizer["VerM"]</a>
                    </p>

                </div>

                <!--Grid column--
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0 float-right">
                    <h5 class="text-uppercase mb-0">Mídias sociais</h5>

                    <ul class="nav">
                        <li>
                            <a href="#" class="fa fa-facebook"></a>
                        </li>
                        <li>

                            <a href="#" class="fa fa-twitter"></a>
                        </li>
                        <li>
                            <a href="#" class="fa fa-linkedin"></a>
                        </li>
                        <li>
                            <a href="#" class="fa fa-instagram"></a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->
                <div class="bg-image hover-overlay hover-zoom hover-shadow ripple" style="margin-left: 200px;">
                    <h5 class="text-center">
                        @Localizer["SocialRedes"]
                    </h5>
                    <a class="btn btn-outline-light btn-social mx-1 mt-3 btn-foursquare" href="https://www.facebook.com/"><i class="fab fa-fw fa-facebook-f fa-lg" style="color: #3B5998 !important;"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1 mt-3" href="https://www.instagram.com/"><i class="fab fa-fw fa-instagram fa-lg" style="color: #3F729B !important;"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1 mt-3" href="https://twitter.com/"><i class="btn-foursquare fab fa-fw fa-twitter fa-lg" style="color: #55ACEE !important;"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1 mt-3" href="https://www.linkedin.com/"><i class="fab fa-fw fa-linkedin-in fa-lg" style="color: #007BB6 !important;"></i></a>
                </div>
            </div>
            <!--Grid row-->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-left p-3" style="background-color: rgba(0, 0, 0, 0.2)">


            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            © 2021 Copyright: Guarda Eventos

        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!-- Footer Social Icons
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Redes Sociais</h4>
                <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
            </div>
            <!-- Footer About Text-
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4">Descrição</h4>
                <p class="lead mb-0">
                    A nossa proposta para o trabalho consiste em criar um aplicação Web com o respetivo tema “Guarda – Candidata a Capital Europeia da Cultura 2027”, cujo nome do WebSite irá ser “Guarda Eventos”.
                </p>
            </div>
        </diZ>
    </div>
        </footer>
        <!-- Copyright Section
        <div class="copyright py-4 text-center text-white">
            <div class="container">
                2020 &copy; Guarda Eventos
            </div>
        </div>



    </footer> -->
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

    <!-- Core theme JS-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script src="~/js/scripts.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

GuardaCapitaldaCultura2027/Views/Shared/_SelecionarLinguagemPartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? $"~/" : $"~{Context.Request.Path.Value}";


    <form asp-controller="Cultura"
          asp-action="SelecionarCultura" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        <button style="border:none;background-color:transparent" type="submit" value="en" name="culture">EN</button>
        <br />
        <button style="border:none;background-color:transparent" type="submit" value="pt" name="culture">PT</button>
    </form>
}