GuardaCapitaldaCultura2027/Models/LugarEvento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GuardaCapitaldaCultura2027.Models
{
    public class LugarEvento
    {
        public int LugarEventoId { get; set; }

        public bool Ocupado { get; set; }


        [Required(ErrorMessage = "Insira o Numero de cadeira")]
        [RegularExpression("[1-9][0-9]{0,2}", ErrorMessage = "Por favor Insira o número de Cadeira valido")]

        public string NumeroCadeira { get; set; }
    }
}

GuardaCapitaldaCultura2027/Controllers/LugarEventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using GuardaCapitaldaCultura2027.Models.ViewModels;

namespace GuardaCapitaldaCultura2027.Controllers
{
    public class LugarEventosController : Controller
    {
        private readonly GuardaEventosBdContext _context;
        private readonly LugaresEvento lugaresEvento;

        public LugarEventosController(GuardaEventosBdContext context)
        {
            _context = context;
            lugaresEvento = new LugaresEvento(context);
        }

        // GET: LugarEventos
        public async Task<IActionResult> Index(int pagina = 1)
        {
            lugaresEvento.Paginacao.PaginaAtual = pagina;
            lugaresEvento.ListaLugares = await _context.LugarEventos.Skip((lugaresEvento.Paginacao.PaginaAtual - 1) * lugaresEvento.Paginacao.ElementosPorPagina).Take(5).ToListAsync();
            return View(lugaresEvento);
        }

        // GET: LugarEventos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lugarEvento = await _context.LugarEventos
                .FirstOrDefaultAsync(m => m.LugarEventoId == id);
            if (lugarEvento == null)
            {
                return NotFound();
            }

            return View(lugarEvento);
        }

        // GET: LugarEventos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LugarEventos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LugarEventoId,Ocupado,NumeroCadeira")] LugarEvento lugarEvento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lugarEvento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lugarEvento);
        }

        // GET: LugarEventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lugarEvento = await _context.LugarEventos.FindAsync(id);
            if (lugarEvento == null)
            {
                return NotFound();
            }
            return View(lugarEvento);
        }

        // POST: LugarEventos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LugarEventoId,Ocupado,NumeroCadeira")] LugarEvento lugarEvento)
        {
            if (id != lugarEvento.LugarEventoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lugarEvento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LugarEventoExists(lugarEvento.LugarEventoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lugarEvento);
        }

        // GET: LugarEventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lugarEvento = await _context.LugarEventos
                .FirstOrDefaultAsync(m => m.LugarEventoId == id);
            if (lugarEvento == null)
            {
                return NotFound();
            }

            return View(lugarEvento);
        }

        // POST: LugarEventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lugarEvento = await _context.LugarEventos.FindAsync(id);
            _context.LugarEventos.Remove(lugarEvento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LugarEventoExists(int id)
        {
            return _context.LugarEventos.Any(e => e.LugarEventoId == id);
        }
    }
}

GuardaCapitaldaCultura2027/Views/LugarEventos/Create.cshtml
@model GuardaCapitaldaCultura2027.Models.LugarEvento
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{ViewData["Title"] = "Create";}

<h4 class="alert-light"> Criar novo Lugar </h4>
<hr />

<div class="col-md-6 text-left">
    <fieldset class="border p-4 list-inline-item">
        <legend class="w-auto text-center font-weight-bold">Formulário de novo Lugar</legend>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ocupado" /> @Html.DisplayNameFor(model => model.Ocupado)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCadeira" class="control-label"></label>
                <input asp-for="NumeroCadeira" class="form-control" />
                <span asp-validation-for="NumeroCadeira" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </fieldset>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GuardaCapitaldaCultura2027/Views/LugarEventos/Delete.cshtml
@model GuardaCapitaldaCultura2027.Models.LugarEvento
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{ ViewData["Title"] = "Delete";}


<!--<center>
    <fieldset class="border p-4" style="width:fit-content;">
        <legend class="w-auto text-left"> Eliminar Lugar </legend>
        <div class="row" style="width:fit-content; padding-left: 20px; padding-right:20px;">
            <table>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Ocupado)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Ocupado)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.NumeroCadeira)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.NumeroCadeira)
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</center>
<br />
<div>
    <a asp-action="Index" class="btn btn-secondary"> Voltar à Lista </a> |
    <a class="btn btn-danger" data-toggle="modal" data-target="#confirmacaoApagar"> Eliminar </a>

<h1>ELiminar</h1>

<h3>Tem mesmo certeza que quer apagar?</h3>
<div>
    <h4>LugarEvento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ocupado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ocupado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCadeira)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCadeira)
        </dd>
    </dl>

    <form asp-action="E">
        <input type="hidden" asp-for="LugarEventoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à Lista</a>
    </form>
</div>

<div id="confirmacaoApagar" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header"><span> Eliminar Lugar </span></div>
            <div class="modal-body"><h6>Tem <b>mesmo</b> certeza que quer apagar?</h6></div>
            <div class="modal-footer">
                <form asp-action="Eliminar">
                    <input type="hidden" asp-for="@Model.LugarEventoId" />
                    <input asp-action="Eliminar" value="Eliminar" type="submit" asp-route-id="@Model.LugarEventoId" class="btn btn-danger" />
                    <a class="btn btn-info" data-dismiss="modal" aria-label="Close"> Fechar </a>
                </form>
            </div>
        </div>
    </div>
</div>

GuardaCapitaldaCultura2027/Views/LugarEventos/Details.cshtml
@model GuardaCapitaldaCultura2027.Models.LugarEvento
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{ViewData["Title"] = "Details";}

<center>
    <fieldset class="border p-4" style="width:fit-content;">
        <legend class="w-auto text-left">Detalhes Eventos</legend>
        <div class="row" style="width:fit-content;padding-left: 20px;padding-right:20px;">
            <table>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Ocupado)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Ocupado)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.NumeroCadeira)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.NumeroCadeira)
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
    <br />
    <div>
        <a asp-action="Index" class="btn btn-secondary"> Voltar à Lista </a> |
        <a asp-action="Edit" asp-route-id="@Model.LugarEventoId" class="btn btn-secondary" style="background-color:goldenrod;border-color:goldenrod;"> Editar </a>
    </div>
</center>
<!--<h1>Detalhes</h1>

<div>
    <h4>Lugar Evento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ocupado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ocupado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCadeira)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCadeira)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model.LugarEventoId">Editar</a> |
    <a asp-action="Index">Voltar à Lista</a>
</div>

GuardaCapitaldaCultura2027/Views/LugarEventos/Edit.cshtml
@model GuardaCapitaldaCultura2027.Models.LugarEvento
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;


@{ViewData["Title"] = "Edit";}

<form enctype="multipart/form-data" asp-action="Edit">
    <div class="col-md-6 text-left">
        <fieldset class="border p-4 list-inline-item">
            <legend class="w-auto text-left"> Editar Lugar </legend>
            <div class="row">
                <div class="col-md-6" style="max-width:100% !important; flex:auto;">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LugarEventoId" />
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Ocupado" /> @Html.DisplayNameFor(model => model.Ocupado)
                        </label>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumeroCadeira" class="control-label"></label>
                        <input asp-for="NumeroCadeira" class="form-control" />
                        <span asp-validation-for="NumeroCadeira" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Editar" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <br />
            <center>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-secondary">Voltar à lista</a> |
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
            </center>
        </fieldset>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GuardaCapitaldaCultura2027/Views/LugarEventos/Index.cshtml
@model GuardaCapitaldaCultura2027.Models.ViewModels.LugaresEvento

@{ ViewData["Title"] = "Index"; }


<fieldset class="border p-4">
    <legend class="w-auto text-left"> Lista dos Lugares Evento</legend>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ListaLugares.FirstOrDefault().Ocupado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ListaLugares.FirstOrDefault().NumeroCadeira)
                </th>
                <th>
                    <form id="pesquisaform" asp-action="Index">
                        <div>
                            @{
                                string pesquisa = "";
                                try
                                {
                                    pesquisa = string.IsNullOrEmpty(Context.Request.Form["pesquisa"]) ? string.Empty : Context.Request.Form["pesquisa"].ToString();

                                }
                                catch (Exception ex)
                                {
                                    Console.WriteLine(ex.Message);
                                }
                                finally
                                {
                                    if (string.IsNullOrEmpty(pesquisa))
                                    {
                                        pesquisa = ViewData["pesquisa"] as string;
                                    }
                                }
                                <input type="search" id="pesquisabox" autofocus oninput="this.form.submit();" onfocus="this.value = '@(pesquisa)'" onchange="this.form.submit()" name="pesquisa" style="margin-right:10px; border: 2px solid #167ce9;font-size: 1.2em;text-align: center;outline:none !important;border-radius: 20px;background-color:transparent;" />
                                <div style="display:none">
                                    @(ViewData["pesquisa"] = pesquisa)
                                </div>
                            }
                            <!--<input type="submit" class="icon-pesquisa fa-7x" value="&#xf002;" style="font-family: FontAwesome;height:35px;width:35px;background-color:transparent;margin-top:1px; border: 2px solid #167ce9;font-size: 1.2em;text-align: center;border-radius: 20px;outline:none !important" />-->
                        </div>
                    </form>
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.ListaLugares.Where(evt =>
        {
            return (!string.IsNullOrWhiteSpace(ViewData["pesquisa"]?.ToString())) ?
              (evt.LugarEventoId.ToString().ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower()) ||
              evt.Ocupado.ToString().Contains(ViewData["pesquisa"]?.ToString().ToLower()) ||
              evt.NumeroCadeira.ToString().ToLower().Contains(ViewData["pesquisa"]?.ToString().ToLower())) : true;
        }).ToList())
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ocupado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroCadeira)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.LugarEventoId" class="btn btn-secondary mr-4" style="background-color:goldenrod;border-color:goldenrod;"> Editar </a>
                    <a asp-action="Details" asp-route-id="@item.LugarEventoId" class="btn btn-info mr-4"> Detalhes </a>
                    <!-- <a asp-action="Delete" asp-route-id="@item.LugarEventoId" class="btn btn-danger"> Eliminar </a> -->
                </td>
            </tr>
        }
        </tbody>
        </table>
        </fieldset>
        <br />
        <p>
            <a asp-action="Create" class="btn btn-primary"> Criar novo Lugar </a>
        </p>
        <div>
            @{ if (Model.Paginacao.PaginaAtual > 1 && Model.Paginacao.PaginaAtual != 2)
                {
                    <a title="Início" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? 1 : Model.Paginacao.PaginaAtual})"><span class="icon-prev"><i style="color:black" class="fas fa-angle-double-left"></i></span></a>
                    <span>&nbsp;</span>
                    <a title="Página Anterior" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? Model.Paginacao.PaginaAtual-1 : Model.Paginacao.PaginaAtual })"><span class="icon-prev"><i style="color:black" class="fas fa-angle-left"></i></span></a>
                    <span>&nbsp;</span> }
                else if (Model.Paginacao.PaginaAtual > 1 && Model.Paginacao.PaginaAtual == 2)
                {
                    <a title="Página Anterior" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual > 1) ? Model.Paginacao.PaginaAtual-1 : Model.Paginacao.PaginaAtual })"><span class="icon-prev"><i style="color:black" class="fas fa-angle-left"></i></span></a>
                    <span>&nbsp;</span> }

                if (Model.Paginacao.PaginaAtual > 2)
                {
                    @Html.ActionLink((Model.Paginacao.PaginaAtual - 1).ToString(), "Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual - 1) }, new { @style = "font-family: 'Varela Round';color:black;font-weight:bolder;" })
                    <span>&nbsp;</span> }

                <span style="font-family: 'Varela Round';color:#167ce9;font-weight:bolder;">@Model.Paginacao.PaginaAtual.ToString()</span>
                <span>&nbsp;</span> if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas - 1)
                {
                    @Html.ActionLink((Model.Paginacao.PaginaAtual + 1).ToString(), "Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual + 1) }, new { @style = "font-family: 'Varela Round';color:black;font-weight:bolder;" })
                    <span>&nbsp;</span> }

                if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas && Model.Paginacao.PaginaAtual + 1 < Model.Paginacao.TotalPaginas)
                {
                    <a title="Página Seguinte" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.PaginaAtual + 1 : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-right"></i></span></a>
                    <span>&nbsp;&nbsp;</span>
                    <a title="Última Página" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.TotalPaginas : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-double-right"></i></span></a>
                    <span>&nbsp;&nbsp;</span> }
                else if (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas && Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas)
                {
                    <a title="Página Seguinte" href="@Url.Action("Index", "LugarEventos", new { @pagina = (Model.Paginacao.PaginaAtual < Model.Paginacao.TotalPaginas) ? Model.Paginacao.PaginaAtual + 1 : Model.Paginacao.PaginaAtual })"><span class="icon-next"><i style="color:black" class="fas fa-angle-right"></i></span></a>
                    <span>&nbsp;&nbsp;</span> } }
        </div>