GuardaCapitaldaCultura2027/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using GuardaCapitaldaCultura2027.Models.ViewModels;

namespace GuardaCapitaldaCultura2027.Controllers
{
    public class HomeController : Controller
    {
        private readonly GuardaEventosBdContext _context;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, GuardaEventosBdContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet("{controller=Home}/{Municipio:alpha}/{page:int?}")]
        public IActionResult Municipios(string Municipio, int? page = 1)
        {
            ViewData["NomeMunicipio"] = Municipio;
            EventosMunicipio eventosDoMunicipio = new EventosMunicipio(_context, Municipio);
            eventosDoMunicipio.Paginacao.PaginaAtual = (int)page;
            eventosDoMunicipio.ListaEventos = eventosDoMunicipio.ListaEventos.Skip(((int)page - 1) * 3).Take(3).ToList();
            return View(eventosDoMunicipio);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sobre()
        {
            return View();
        }

        public IActionResult Contactos()
        {
            return View();
        }

        public IActionResult Turista()
        {
            return View();
        }

        /*public IActionResult Aguiar()
        {
            return View();
        }   
        public IActionResult Almeida()
        {
            return View();
        }
        public  IActionResult Belmonte()
        {
            return View();
        }

        public IActionResult Celorico()
        {
            return View();
        }

        public IActionResult Covilha()
        {
            return View();
        }
        public IActionResult FCR()
        {
            return View();
        }
        public IActionResult Fornos()
        {
            return View();
        }
        public IActionResult Fundao()
        {
            return View();
        }
        public IActionResult Gouveia()
        {
            return View();
        }
        public IActionResult Guarda()
        {
            return View();
        }
        public IActionResult Manteigas()
        {
            return View();
        }
        public IActionResult Meda()
        {
            return View();
        }
        public IActionResult Pinhel()
        {
            return View();
        }
        public IActionResult Sabugal()
        {
            return View();
        }

        public IActionResult Seia()
        {
            return View();
        }

        public IActionResult Trancoso()
        {
            return View();
        }

        public IActionResult VNFC()
        {
            return View();
        }*/
        public IActionResult Erro()
        {
            return View();
        }

        public IActionResult Covid()

        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }    
        
    }
}

GuardaCapitaldaCultura2027/Controllers/MunicipiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace GuardaCapitaldaCultura2027.Controllers
{   
    //[Authorize(Roles = "Admin, GestorEventos")]
    public class MunicipiosController : Controller
    {
        private readonly GuardaEventosBdContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

      

        public MunicipiosController(GuardaEventosBdContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        // GET: Municipios
        public IActionResult Index(string nome = null, int page = 1)
        {
            var pagination = new PagingInfoMunicipio
            {
                CurrentPage = page,
                PageSize = PagingInfoMunicipio.DEFAULT_PAGE_SIZE,
                TotalItems = _context.Municipio.Where(p => nome == null || p.Nome.Contains(nome)).Count()
            };

            return View(
                    //await _context.Municipios.ToListAsync()
                    new ListaMunicipio
                    {
                        Municipios = _context.Municipio.Where(p => nome == null || p.Nome.Contains(nome))
                            .OrderBy(p => p.Nome)
                            .Skip((page - 1) * pagination.PageSize)
                            .Take(pagination.PageSize),
                        pagination = pagination,
                        SearchNome = nome
                    }
                );
        }

        // GET: Municipios
        public async Task<IActionResult> Page()
        {
            return View(await _context.Municipio.ToListAsync());
        }



        // GET: Municipios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipio
                .FirstOrDefaultAsync(m => m.MunicipioId == id);
            if (municipio == null)
            {
                return NotFound();
            }

            return View(municipio);
        }

        // GET: Municipios/Create
        [Authorize(Roles = "Admin, GestorEventos")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Municipios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Create([Bind("MuicipioId,Nome,Data_imagem,Descricao,Desativar")] Municipio municipio, List<IFormFile> Imagem)
        {
            if (ModelState.IsValid)
            {
                //conversao da imagem para binario
                foreach (var item in Imagem)
                {
                    if (item.Length > 0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            await item.CopyToAsync(stream);
                            municipio.Imagem = stream.ToArray();
                        }
                    }
                }
             


                //incerir 
                _context.Add(municipio);
                await _context.SaveChangesAsync();
                /*****Mensagem de sucesso ******/
                ViewBag.title = "Municipio criado Com Sucesso!";
                ViewBag.type = "alert-success";
                ViewBag.message = "Municipio criado!";
                ViewBag.redirect = "/Municipios/Index"; // Request.Path
                return View("Mensagem");

            }
            return View(municipio);
        }

        [Authorize(Roles = "Admin, GestorEventos")]
        // GET: Municipios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipio.FindAsync(id);
            if (municipio == null)
            {
                return NotFound();
            }
            return View(municipio);
        }

        // POST: Municipios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Edit(int id, [Bind("MunicipioId,Nome,Data_imagem,Desativar,Descricao")] Municipio municipio, List<IFormFile> Imagem)
        {
            if (id != municipio.MunicipioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var item in Imagem)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                municipio.Imagem = stream.ToArray();
                            }
                        }
                    }

                    Municipio VerificarDados = await _context.Municipio.FindAsync(id);
                    VerificarDados.Nome = municipio.Nome;
                    VerificarDados.Descricao = municipio.Descricao;
                    VerificarDados.Desativar = municipio.Desativar;


                    municipio = VerificarDados;

                    _context.Update(municipio);
                    await _context.SaveChangesAsync();
                    ViewBag.title = "Municipio Atualizado Com Sucesso!";
                    ViewBag.type = "alert-success";
                    ViewBag.message = "Municipio Atualizado!";
                    ViewBag.redirect = "/Municipios/Index"; // Request.Path
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MunicipioExists(municipio.MunicipioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Mensagem");
                //return RedirectToAction(nameof(Index));
            }
            return View(municipio);
        }

        // GET: Municipios/Delete/5
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var municipio = await _context.Municipio
                .FirstOrDefaultAsync(m => m.MunicipioId == id);
            if (municipio == null)
            {
                return NotFound();
            }

            return View(municipio);
        }

        // POST: Municipios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, GestorEventos")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var municipio = await _context.Municipio.FindAsync(id);
            _context.Municipio.Remove(municipio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MunicipioExists(int id)
        {
            return _context.Municipio.Any(e => e.MunicipioId == id);
        }
    }
}

GuardaCapitaldaCultura2027/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GuardaCapitaldaCultura2027.Models;
using GuardaCapitaldaCultura2027.Models.Context;
using GuardaCapitaldaCultura2027.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GuardaCapitaldaCultura2027.Controllers
{
    [Authorize]
    public class ReservasController : Controller
    {
        private readonly Reservas Reservas;
        private readonly UserManager<IdentityUser> UserManager;
        private readonly GuardaEventosBdContext _context;
        private readonly IdentityUser SignedInUser;

        public ReservasController(GuardaEventosBdContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            Reservas = new Reservas(context);
            UserManager = userManager;            
            SignedInUser = userManager.FindByNameAsync(signInManager.Context.User.Identity.Name).GetAwaiter().GetResult();
        }

        // GET: Reserva
        public ActionResult Index(int page = 1)
        {
            Reservas.Paginacao.PaginaAtual = page;
            Reservas.ListaReservas = _context.Reservas.Include(rsv => rsv.Evento).Where(rsv => rsv.PessoaId.Equals(SignedInUser.Id)).Skip((Reservas.Paginacao.PaginaAtual - 1) * Reservas.Paginacao.ElementosPorPagina).Take(Reservas.Paginacao.ElementosPorPagina).ToList();
            return View(Reservas);
        }

        // GET: Reserva/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas.Include(rsv => rsv.Evento)
                .FirstOrDefaultAsync(m => m.ReservaId == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reserva/Create
        public ActionResult Create(int EventoId)
        {
            return View(new Reserva() { EventoId = EventoId, PessoaId = SignedInUser.Id});
        }

        // POST: Reserva/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync([Bind("ReservaId, EventoId, PessoaId, Nome, Observacao, Numero_Reserva")] Reserva reserva)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reserva);
        }

        // GET: Reserva/Edit/5
        public async Task<ActionResult> EditAsync(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas.Include(rsv => rsv.Evento).Where(rsv => rsv.ReservaId==id).FirstOrDefaultAsync();
            
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reserva/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, [Bind("ReservaId, EventoId, PessoaId, Nome, Observacao, Numero_Reserva")] Reserva reserva)
        {
            if (id != reserva.ReservaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserva);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservaExists(reserva.ReservaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reserva);
        }

        // GET: Reserva/Delete/5
        public async Task<ActionResult> DeleteAsync(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .FirstOrDefaultAsync(m => m.ReservaId == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reserva/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(int id, IFormCollection collection)
        {
            var reserva = await _context.Reservas.FindAsync(id);
            _context.Reservas.Remove(reserva);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ReservaExists(int id)
        {
            return _context.Reservas.Any(r => r.ReservaId == id);
        }
    }
}

GuardaCapitaldaCultura2027/Views/Home/Covid.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization;

@{
    ViewData["Title"] = "Informações Covid-19";
}


<div id="demo" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
    </ul>

    <!-- The slideshow -->
    <div class="carousel-inner ">
        <div class="carousel-item active">
            <img src="https://covid19.min-saude.pt/wp-content/uploads/2020/03/banner_sintomas_sns241.jpg" alt="Banner Sintomas" width="1100" height="300">
        </div>
        <div class="carousel-item">
            <img src="https://covid19.min-saude.pt/wp-content/uploads/2020/09/banner_dgs_Stayway-covid-01.png" alt="Barner Stayway Covid" width="1100" height="300">
        </div>
        <div class="carousel-item">
            <img src="https://covid19.min-saude.pt/wp-content/uploads/2020/03/banner_seguranca_social-1-scaled.jpg" alt="Barner Segurança Social" width="1100" height="300">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
<div class="m-5"></div>
<div class="alert alert-light text-justify" role="alert">
    
    <h4 class="alert-heading">@Localizer["TituloCovid"]</h4>
    <p>
        @Localizer["TituloCovid1"]<br>
        <br>
        @Localizer["TituloCovid2"]
        <br>
        <br>
        @Localizer["TituloCovid3"]
        <br>
        <br>
        @Localizer["TituloCovid4"]
       <br>
        <br>
    </p>
</div>

<hr>
<section class="av_textblock_section text-justify alert alert-light text-justify" itemscope="itemscope" itemtype="https://schema.org/CreativeWork">
    <div class="avia_textblock  " style="font-size:20px; " itemprop="text">
        <p>
            <strong>
                <span style="color: #707070;">
                    @Localizer["TituloCovid5"]
                    <br>
                </span>
            </strong>
            @Localizer["TituloCovid6"]
           
        </p>
        <p><strong><span style="color: #707070;">&nbsp;</span></strong></p>
    </div>
</section>
<hr>
<section class="avia_codeblock_section  av-small-hide av-mini-hide avia_code_block_1" itemscope="itemscope" itemtype="https://schema.org/CreativeWork">
    <div class="avia_codeblock " itemprop="text">
        <iframe src="https://esriportugal.maps.arcgis.com/apps/opsdashboard/index.html#/acf023da9a0b4f9dbb2332c13f635829" style="width:100%;" height="800" frameborder="0">
        </iframe>
    </div>
</section>

GuardaCapitaldaCultura2027/Views/Home/Erro.cshtml
@{
    ViewData["Title"] = "Erro";
}

<div class="text-center">
    <h1 class="display-4">Erro!</h1>
    <p>Ainda estamos em contrução!</p>
</div>

GuardaCapitaldaCultura2027/Views/Home/Index.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization;

@{
    ViewData["Title"] = "Home Page";
}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <a asp-controller="Home" asp-action="Covid" class="text-black-50">
        <strong>COVID-19!</strong>@Localizer["AleteCovid"]
    </a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/img/CAPITAL-EUROPA.jpg" alt="Primeiro Slide" />
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/CAPITAL-EUROPA.jpg" alt="Segundo Slide" />
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/CAPITAL-EUROPA.jpg" alt="Terceiro Slide" />
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/sustentabilidade1.png" alt="Terceiro Slide" width="1097" height="427" />
            <div class="carousel-caption d-none d-md-block">
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Próximo</span>
    </a>
</div>

<div class="m-5"></div>
<div class="row">
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Aguiar">
                <img class="card-img-top" src="~/img/src/12.jpg" alt="Município de Aguiar da Beira" height="200">
                <div class="overlay2">Aguiar da Beira</div>
            </a>

        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Almeida">
                <img class="card-img-top" src="~/img/src/3.jpg" alt="Município de Almeida" height="200">
                <div class="overlay2">Almeida</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Belmonte">
                <img class="card-img-top" src="~/img/src/4.jpg" alt="Município de Belmonte" height="200">
                <div class="overlay2">Belmonte</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Celorico">
                <img class="card-img-top" src="~/img/src/5.jpg" alt="Município de Celorico da Beira" height="200">
                <div class="overlay2">Celorico da Beira</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Covilha">
                <img class="card-img-top" src="~/img/src/6.jpg" alt="Município de Covilhã" height="200">
                <div class="overlay2">Covilhã</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="FCR">
                <img class="card-img-top" src="~/img/src/7.jpg" alt="Município de Figueira de Castelo Rodrigo" height="200">
                <div class="overlay2">Figueira de Castelo Rodrigo</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Fornos">
                <img class="card-img-top" src="~/img/src/8.jpg" alt="Município de Fornos de Algodres" height="200">
                <div class="overlay2">Fornos de Algodres</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Fundao">
                <img class="card-img-top" src="~/img/src/9.jpg" alt="Município de Fundão" height="200">
                <div class="overlay2">Fundão</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Gouveia">
                <img class="card-img-top" src="~/img/src/10.jpg" alt="Município de Gouveia" height="200">
                <div class="overlay2">Gouveia</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Guarda">
                <img class="card-img-top" src="~/img/src/11.jpg" alt="Município de Guarda" height="200">
                <div class="overlay2">Guarda</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Manteigas">
                <img class="card-img-top" src="~/img/src/12.jpg" alt="Município de Manteigas" height="200">
                <div class="overlay2">Manteigas</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Meda">
                <img class="card-img-top" src="~/img/src/13.jpg" alt="Município de Mêda" height="200">
                <div class="overlay2">Mêda</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Pinhel">
                <img class="card-img-top" src="~/img/src/14.jpg" alt="Município de Pinhel" height="200">
                <div class="overlay2">Pinhel</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Sabugal">
                <img class="card-img-top" src="~/img/src/15.jpg" alt="Município de Sabugal" height="200">
                <div class="overlay2">Sabugal</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Seia">
                <img class="card-img-top" src="~/img/src/15.jpg" alt="Município de Seia" height="200">
                <div class="overlay2">Seia</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="Trancoso">
                <img class="card-img-top" src="~/img/src/2.jpg" alt="Município de Trancoso" height="200">
                <div class="overlay2">Trancoso</div>
            </a>
        </div>
    </div>
    <div class="col-md-4 mb-5 ">
        <div class="zoom card h-100">
            <a asp-controller="Home" asp-action="VNFC">
                <img class="card-img-top" src="~/img/src/4.jpg" alt="Município de Vila Nova de Foz Côa" height="200">
                <div class="overlay2">Vila Nova de Foz Côa</div>
            </a>
        </div>
    </div>


</div>
<!-- /.row -->

GuardaCapitaldaCultura2027/Views/Home/_EventoPartial.cshtml
@model Evento

<script type="text/javascript">
    function EsconderTexto(id) {
        if ($('#desc' + id).hasClass('hidden')) {
            $('#desc' + id).attr('style', 'white-space:unset;overflow:unset;text-overflow:unset;');
            $('#desc' + id).removeClass('hidden');
            $('#verMais' + id).text('Ver Menos');
        }
        else {
            $('#desc' + id).attr('style', 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;');
            $('#desc' + id).addClass('hidden');
            $('#verMais' + id).text('Ver Mais');
        }
    }
</script>

<div class="col-xs-12 col-sm-6 col-md-4">
    <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
        <div class="mainflip">
            <div class="frontside">
                <div class="card">
                    <div class="card-body text-center">

                        <img style="width: 100%; height: 128px; margin-bottom:10px;"
                             src="data:image/*;base64, @(Convert.ToBase64String(Model.Imagem))" />
                        <h4 class="card-title">@Model.Name</h4>
                        <p id=@("desc" + Model.EventoId) class="card-text hidden" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">@Model.Descricao</p>
                        <a id=@("verMais" + Model.EventoId) href="#" style="border:none;" onclick="EsconderTexto(@Model.EventoId)">Ver Mais</a>
                        <br/>
                        <p class="card-text">@(Model.Data_realizacao.ToShortDateString())</p>
                        @Html.ActionLink("Reservar", "Create", "Reservas", new { @EventoId = Model.EventoId })
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>